# This is a basic workflow

name: Send Free email.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Runs a set of commands using the runners shell
      - name: Install mailutils
        run: |
          sudo apt install -y mailutils
          echo "Make the most out of Linux!" | mail -s "Welcome to Linux" niyonkuruelisa@gmail.com
      # Runs a set of commands using the runners shell
      - name: Send email
        run: |
          echo "Welcome to your new Linux system! Here are some tips to get started."
          mail -s "Welcome to Linux" niyonkuruelisa@gmail.com
          sudo tail -f /var/log/mail.log

